name = "personal-embeds"
main = "src/index.js"
compatibility_date = "2023-12-01"

# For local development only - remove or comment out before committing
[vars]
BETTERSTACK_SOURCE_TOKEN = "Z2BjBhLQ3ub84LE94nx6cwa9"

# For production, use secrets instead:
# Run: npx wrangler secret put BETTERSTACK_SOURCE_TOKEN

[env.production]
name = "personal-embeds-production" 